name: Build and deploy to gh-pages
on:
   push:
     branches:
       - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üì•
        uses: actions/checkout@v2.4.0
        with:
          token: '${{ secrets.GHPAGES_ACTION_CHECKOUT_TOKEN_PAT }}'

      - name: Install dependencies üêÑ
        run: |
          sudo apt-get -y update
          sudo apt-get -y install python3-pip
          pip install mkdocs-material==7.3.6 pygments==2.10.0 mkdocs-redirects==1.0.3

      - name: Build site üîß
        run: |
          mkdocs build --verbose --clean

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: '${{ secrets.GHPAGES_ACTION_DEPLOY_TOKEN_PAT }}'
          git-config-name: '${{ secrets.GHPAGES_ACTION_DEPLOY_GITNAME_PAT }}'
          git-config-email: '${{ secrets.GHPAGES_ACTION_DEPLOY_GITEMAIL_PAT }}'
          branch: gh-pages # The branch the action should deploy to.
          folder: site # The folder the action should deploy.
